#!/bin/bash

docker-compose -f janus1/docker-compose.yml down;
docker-compose -f janus1/docker-compose.yml up -d;   
docker-compose -f janus2/docker-compose.yml down;
docker-compose -f janus2/docker-compose.yml up -d;