#!/bin/bash

source .env

session_id=$(curl -X POST ${janus1_server} -d "{
  \"janus\": \"create\",
  \"transaction\": \"${transaction}\"}" 2>/dev/null  | awk -F ' ' '/\"id\"/ {print $2}');
echo "Session id: $session_id";

handle_id=$(curl -X POST ${janus1_server}/$session_id --data "{
  \"transaction\": \"${transaction}\", 
  \"janus\": \"attach\", 
  \"plugin\":\"janus.plugin.videoroom\"}" 2>/dev/null | awk -F ' ' '/\"id\"/ {print $2}');
echo "Handle id: $handle_id" ;

curl -X POST ${janus1_server}/$session_id/$handle_id --data "{
  \"transaction\": \"${transaction}\", 
  \"janus\": \"message\", 
  \"body\": {
    \"request\": \"create\", 
    \"room\": ${room_id}, 
    \"publishers\": ${max_publishers}, 
    \"bitrate\":128000, 
    \"record\": false, 
    \"description\": \"${transaction}\", 
    \"fir_freq\": 100}}"  2>/dev/null;
