#!/bin/bash

source .env

session_id=$(curl -X POST ${janus1_server} -d "{
  \"janus\": \"create\",
  \"transaction\": \"${transaction}\"}" 2>/dev/null  | awk -F ' ' '/\"id\"/ {print $2}');
echo "Session id: $session_id";

handle_id=$(curl -X POST ${janus1_server}/$session_id --data "{
  \"transaction\": \"${transaction}\", 
  \"janus\": \"attach\", 
  \"plugin\":\"janus.plugin.videoroom\"}" 2>/dev/null | awk -F ' ' '/\"id\"/ {print $2}');
echo "Handle id: $handle_id" ;

user_id=$(curl -X POST ${janus1_server}/$session_id/$handle_id --data "{
  \"transaction\": \"${transaction}\", 
  \"janus\": \"message\", 
  \"body\": {
    \"request\": \"listparticipants\", 
    \"room\": ${room_id}}}" 2>/dev/null | awk -F ' ' '/\"id\"/ {print $2}' | cut -d ',' -f 1);
echo "User id: $user_id";

curl -X POST ${janus1_server}/$session_id/$handle_id --data "{ 
  \"transaction\": \"${transaction}\", 
  \"janus\": \"message\", 
  \"body\": { 
    \"request\": \"stop_rtp_forward\", 
    \"room\": ${room_id}, 
    \"stream_id\": 121345892, 
    \"publisher_id\": $user_id}}" ;