- hosts: janus
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  tasks:

  # remove docker first
  - name: Purge Docker
    shell: "apt purge -y docker-engine docker docker.io docker-ce"
  
  - name: Remove Docker
    shell: "apt remove -y docker docker-engine docker.io containerd docker-ce runc"
  
  - name: Autoremove Docker
    shell: "apt autoremove -y --purge docker-engine docker docker.io docker-ce "

  - name: Clean docker dir
    file:
      state: absent
      path: "{{ item }}"
    loop:
       - /var/lib/docker 
       - /etc/docker
       - /etc/apparmor.d/docker
       - /var/lib/containerd
       - /etc/apparmor.d/docker
       - /var/run/docker.sock
       - /usr/local/bin/docker-compose
    
  - name: Reboot box if kernel/libs updated and requested by the system
    shell: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed' 
    args:
        removes: /var/run/reboot-required
    async: 300
    poll: 0
    ignore_errors: true
  
  - name: Wait for system to become reachable again
    wait_for_connection:
      delay: 60
      timeout: 300